### ISSUE TITLE
Shoestring compatibility?

### ISSUE THREAD

**Issue by beep** [filamentgroup/responsive-carousel#113]
Just curious: any plans for shoestring compatibility? When loading responsive-carousel.js core alongside [shoestring](https://github.com/filamentgroup/shoestring), I get a `$.Event is not a function` error when navigating previous/next in the carousel.

**Comment by beep** [comment]
Whoops, hit “post” prematurely. Please disregard. I’m terrible at things.

**Comment by johnbender** [comment]
Github makes it hard to find newer releases without uploads or flowery language :-1:

**Comment by beep** [comment]
Belay that: grabbing [the latest release](https://github.com/filamentgroup/responsive-carousel/releases/tag/v0.2.6) (which is hidden by default on the releases page? github why?) resolves the error. EVERYTHING IS GOOD
