### ISSUE TITLE
touch: if you tap next/prev link during a transition, it can disable those links semi-permanently

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/responsive-carousel#155]

**Comment by johnbender** [comment]
@scottjehl 

https://github.com/filamentgroup/responsive-carousel/compare/155

Not ready to merge yet.

How should I set up the CSS, it's currently only on the `slide-two.html` functional test page. Wasn't sure about the best way to scope it.

I did my level best not to butcher the drag code.

**Comment by johnbender** [comment]
Preview: https://155-origin-responsive-carousel.fgview.com/test/functional/slide-two.html
