### ISSUE TITLE
If Prev/Next buttons are positioned at the top of the slider--- all responsive functionality breaks

### ISSUE THREAD

**Issue by iamcarrico** [filamentgroup/responsive-carousel#32]
When we enabled the dynamic-containers plugin, we noticed that as we changed window sizes, the functionality will completely break if the prev and next buttons are at the same height as the first element. This is due to the '$( this ).offset().top !== prev.offset().top'  being the same as the prev. and next buttons are within the same div.

Although I think this can be solved by CSS, this might not be desirable if the design wants the buttons to be up top. Could also be helpful to have the previous and next buttons outside of the container, and just have the first element be automatically added to the first container no matter what.

**Comment by ramiroazar** [comment]
This issue can be replicated within the [Dynamic responsive containers](http://filamentgroup.github.io/responsive-carousel/test/functional/responsive-containers.html) demo by changing the absolute positioning of **.carousel-nav** from **bottom** to **top** and resizing the viewport.

This results in `Uncaught TypeError: Cannot read property 'push' of undefined` on line **43** of **responsive-carousel.dynamic-containers.js**
