### ISSUE TITLE
build / dist issue?

### ISSUE THREAD

**Issue by beep** [filamentgroup/responsive-carousel#83]
Having a couple issues with the `dist`ed `carousel.min.js`:
1. `<banner:meta.banner>` seems to be inserted as a string literal at the top of the JS file.
   - This error occurs regardless of whether I build the file myself, or grab it from the 0.2.0 dist on [the releases page](https://github.com/filamentgroup/responsive-carousel/releases).
2. Manually removing `<banner:meta.banner>` from the dist nets me a `SyntaxError: function statement requires a name` error.

Any chance I did something wrong? I’m good at that.

Thanks!

**Comment by klamping** [comment]
I ran in to this same issue today. Mind pushing a PR/release out to fix this?
